version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: cmd123456
       MYSQL_DATABASE: cmd_database
       MYSQL_USER: cmd_user
       MYSQL_PASSWORD: cmd_123456789

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: cmd_user
       WORDPRESS_DB_PASSWORD: cmd_123456789
       WORDPRESS_DB_NAME: cmd_database
volumes:
    db_data: {}